spring:
  main:
    allow-bean-definition-overriding: true

  #redis 配置
  redis:
    host: localhost
    password:
    database: 0
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/remote
    username: root
    password: 123456wjf

feign:
  user:
    server-name: remote
    url: http://localhost:8899

kafka:
  server:
  max-block-ms: 10000
  topic: sci_test_data_beibo
