spring:
  main:
    allow-bean-definition-overriding: true

  #redis 配置
  redis:
    host: localhost
    password:
    database: 0
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/remote
    username: root
    password: 123456wjf

feign:
  user:
    server-name: remote
    url: http://localhost:8899

kafka:
  bootstrap-servers: 127.0.0.1:9092
  consumer:
    group-id: 0
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    batch-size: 65536
    buffer-memory: 524288