spring:
  # 配置启动的配置文件
  profiles:
    active: local

#服务器相关配置
server:
  port: 8080
  undertow:
    accesslog:
      pattern: combined
      enabled: true
      dir: /data/logs

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka